### ISSUE TITLE
choose category instead of entering ID

### ISSUE THREAD

**Issue by Tazzios** [JoomGalleryfriends/JoomTreeView#2]
I was trying to figure out how i can change the module so that you can choose an root category instead entering an number. 

Changing  extension="com_content" to extension="com_joomgallery" did not work. (would be to easy) 
But i also could not find which files/function are called for these to below that do work. Heck, I could rename the both of the component folders and it still worked.
```
<field
  name="catid2"
  type="category"
  label="JCATEGORY"
  description="MOD_POPULAR_FIELD_CATEGORY_DESC"
  extension="com_content"
  multiple="true"
  filter="int_array"
/>

<field
  name="catid"
  type="category"
  label="JCATEGORY"
  description="MOD_POPULAR_FIELD_CATEGORY_DESC"
  extension="com_jevents"
  multiple="true"
  filter="int_array"
/>
```
Can some one point me in the right direction?

If i got it working i can do the same changes for other modules.

**Comment by MrMusic** [comment]
Please test https://github.com/JoomGalleryfriends/JoomTreeView/pull/4

**Comment by Tazzios** [comment]
@MrMusic just tested and works great. :) 
I'm only not sure of showing the ID number. You show the complete structure of the categorys so even if you have categorys with the same name it still would be clear which one you have.

**Comment by MrMusic** [comment]
>I'm only not sure of showing the ID number. You show the complete structure of the categorys so even if you have categorys with the same name it still would be clear which one you have.

Until now, you could only enter the ID. Now you can choose from the category structure.
Since the ID is still displayed, it is still possible to search and using the ID (for backward compatibility).
